const products = [
  {
    id: "tab-12",
    name: "Tab 12",
    category: "Portable",
    size: "12 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_7832a7f213cf459d8403c7460a991e2e~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/T%2012_f.png",
    description:
      "Designed for effortless on-site use, this ultra-simple teleprompter supports an iPad or tablet and features a foldable design for easy transport. Its quick and intuitive setup makes it perfect for on-location filming.",
    features: [
      "Supports iPad or tablet",
      "Foldable, portable design",
      "Quick, intuitive setup",
      "Optimized for on-location filming",
    ],
    specs: [
      { label: "Overall Structure", value: "Folding Type (adjustable angle)" },
      { label: "Attachable Tablet", value: "Max 13.1-inch Tablet" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Camera Quick Shoe", value: "Standard Mount" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard)" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Body Lens Hole Size", value: "Width 270mm × Height 235mm" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Wireless Remote Dongle", value: "Tablet C-type USB Dongle" },
      { label: "Base Size", value: "W 275mm × D 235mm" },
      { label: "Product Folding Size", value: "W 365mm × D 410mm × H 200mm" },
      { label: "Product Body Size", value: "W 365mm × D 300mm × H 325mm (excluding plate)" },
      { label: "Product Overall Size", value: "W 365mm × D 485mm × H 325mm" },
      { label: "Product Overall Weight", value: "5.02 kg" },
      { label: "Hard Case", value: "Wood & Plastic combination (optional purchase)" },
    ],
    bestFor: "On-location filming, creators using iPad or tablet",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "flex-15",
    name: "Flex 15",
    category: "Portable",
    size: "15.6 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_f6b3fc7a759942a780f6c70627fe7a45~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/f%2015.png",
    description:
      "A portable teleprompter designed for larger screen needs in the field. It works with laptops up to 15.6 inches, offering excellent cost efficiency. With its foldable, easy-to-assemble design, it’s ideal for both studio and on-site use.",
    features: [
      "Supports laptops up to 15.6 inches",
      "Foldable, easy-to-assemble design",
      "Portable for studio and on-site use",
      "Cost-efficient larger-screen setup",
    ],
    specs: [
      { label: "Overall Structure", value: "Folding Type (adjustable angle)" },
      { label: "Attachable Tablet", value: "Max 13.1-inch Tablet" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Camera Quick Shoe", value: "Standard Mount" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard)" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Body Lens Hole Size", value: "Width 270mm × Height 235mm" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Wireless Remote Dongle", value: "Tablet C-type USB Dongle" },
      { label: "Base Size", value: "W 350mm × D 260mm" },
      { label: "Product Folding Size", value: "W 440mm × D 460mm × H 215mm" },
      { label: "Product Body Size", value: "W 440mm × D 335mm × H 345mm (excluding plate)" },
      { label: "Product Overall Size", value: "W 440mm × D 520mm × H 355mm" },
      { label: "Product Overall Weight", value: "5.78 kg" },
      { label: "Hard Case", value: "Wood & Plastic combination (optional purchase)" },
    ],
    bestFor: "Studio and on-site productions needing laptop support",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "clone-16",
    name: "Clone 16",
    category: "Portable",
    size: "16 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_7105d15163c240729eaa6cb65ac8b043~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/cl%2016.png",
    description:
      "A portable teleprompter that connects to a laptop via HDMI for faster, more stable production. Ideal for interviews and product shoots, it allows instant script editing and smooth control. Its 16:9 widescreen display offers a wider view, replacing traditional 17-inch 4:3 models.",
    features: [
      "HDMI laptop connection",
      "16:9 widescreen viewing",
      "Fast, stable production workflow",
      "Ideal for interviews and product shoots",
    ],
    specs: [
      { label: "Overall Structure", value: "Folding Type (adjustable angle)" },
      { label: "Panel Size", value: "15.6\"" },
      { label: "Monitor Active Area", value: "W 560mm × H 490mm" },
      { label: "Resolution", value: "1280 × 720" },
      { label: "Aspect Ratio", value: "16:9, 4:3" },
      { label: "Monitor Brightness", value: "400 cds" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 5A Power Adapter" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard)" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Body Lens Hole Size", value: "Width 270mm × Height 235mm" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Product Folding Size", value: "W 410mm × D 380mm × H 210mm" },
      { label: "Product Body Size", value: "W 410mm × D 260mm × H 310mm (excluding plate)" },
      { label: "Product Overall Size", value: "W 410mm × D 520mm × H 310mm" },
      { label: "Product Overall Weight", value: "6.98 kg" },
      { label: "Hard Case", value: "Wood & Plastic combination (optional purchase)" },
    ],
    bestFor: "Interviews, product shoots, fast script editing",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "spot-18",
    name: "Spot 18",
    category: "Spot",
    size: "18 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_b258d0d5a45548ce9226fae4b6b2931a~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/s%2018.png",
    description:
      "The first 18-inch teleprompter built for both studio and field use, combining a large display with easy portability. Ideal for medium-sized teams, it features a 16:9 widescreen monitor with a switchable 4:3 mode for flexible script use.",
    features: [
      "18-inch display for studio and field",
      "Large display with easy portability",
      "16:9 monitor with switchable 4:3 mode",
      "Designed for medium-sized teams",
    ],
    specs: [
      { label: "Overall Structure", value: "Folding Type (adjustable angle)" },
      { label: "Panel Size", value: "17.3\"" },
      { label: "Monitor Active Area", value: "W 560mm × H 490mm" },
      { label: "Resolution", value: "1920 × 1080" },
      { label: "Aspect Ratio", value: "16:9 / 4:3" },
      { label: "Monitor Brightness", value: "Max 1000 cds (adjustable)" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 5A Power Adapter" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard)" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Body Lens Hole Size", value: "Width 270mm × Height 235mm" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Product Folding Size", value: "W 550mm × D 490mm × 245mm" },
      { label: "Product Body Size", value: "W 550mm × D 350mm × 375mm (excluding plate)" },
      { label: "Product Overall Size", value: "W 550mm × D 580mm × 385mm" },
      { label: "Product Overall Weight", value: "12.5 kg" },
      { label: "Hard Case", value: "Wood & Plastic Combination (optional purchase)" },
    ],
    bestFor: "Studio + field teams needing a mid-size display",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "folder-22n",
    name: "Folder 22N",
    category: "Spot",
    size: "22 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_ac5218148a4e4920964186ca934a2c72~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/f%2022n.png",
    description:
      "The first 22-inch high-brightness teleprompter for both studio and field use, combining a large display with portability. The Folder 22N offers high-end, cost-efficient performance with a 16:9 widescreen format and switchable 4:3 mode for flexible production.",
    features: [
      "22-inch high-brightness display",
      "Studio and field ready",
      "16:9 format with switchable 4:3",
      "High-end, cost-efficient performance",
    ],
    specs: [
      { label: "Overall Structure", value: "Folding Type (adjustable angle)" },
      { label: "Panel Size", value: "21.5\"" },
      { label: "Monitor Active Area", value: "W 560mm × H 490mm" },
      { label: "Resolution", value: "1920 × 1080" },
      { label: "Aspect Ratio", value: "16:9 / 4:3" },
      { label: "Monitor Brightness", value: "Max 1000 cds (adjustable)" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 5A Power Adapter" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard)" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Body Lens Hole Size", value: "Width 270mm × Height 235mm" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Power Strip", value: "Built-in power strip with four or more outlets" },
      { label: "Hard Case", value: "Wood & Plastic Combination (optional purchase)" },
      { label: "Product Body Size", value: "W 560mm × D 490mm × 420mm (excluding plate)" },
      { label: "Product Overall Size", value: "W 560mm × D 490mm × 550mm" },
      { label: "Product Weight", value: "14.1 kg (excluding plate)" },
      { label: "Product Overall Weight", value: "17.0 kg" },
    ],
    bestFor: "Portable high-brightness teleprompter use",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "cue-24",
    name: "Cue 24",
    category: "Cue",
    size: "24 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_a36e5bf9e50449b294ec877e9525391c~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/c%2024.png",
    description:
      "An innovative teleprompter that delivers exceptional video quality for everyone — from professionals to beginners. Featuring a 24-inch, 1000 cd/m², 16:9 high-brightness monitor, it’s a powerful, mid-sized model built for both studio and on-location production.",
    features: [
      "24-inch 16:9 display",
      "1000 cd/m² high brightness",
      "Built for studio and on-location production",
      "Mid-sized, professional performance",
    ],
    specs: [
      { label: "Panel Size", value: "23.8\"" },
      { label: "Monitor Active Area", value: "W 522mm × H 297mm" },
      { label: "Resolution", value: "1920 × 1080" },
      { label: "Aspect Ratio", value: "16:9, 4:3" },
      { label: "Monitor Brightness", value: "Max 1000 cds (adjustable)" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 5A Power Adapter" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard) / Plastic" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Body Lens Hole Size", value: "Upper 360 Bottom 300 Height 320" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Hood Size", value: "Upper 610 Lower 520 Height 535" },
      { label: "Hood Weight", value: "5.00 kg" },
      { label: "Monitor Size", value: "W 580mm × D 350mm × H 45mm" },
      { label: "Monitor Weight", value: "3.31 kg" },
      { label: "Product Overall Size", value: "W 610mm × D 540mm × H 440mm" },
      { label: "Product Overall Weight", value: "11.31 kg" },
    ],
    bestFor: "Studios and on-location crews needing 24-inch clarity",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "cue-27",
    name: "Cue 27",
    category: "Cue",
    size: "27 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_5255d1b2f860492ebef0d04aa98144bf~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/c%2027.png",
    description:
      "A high-performance teleprompter that delivers exceptional video quality for professionals and everyday creators. With its 27-inch, 1000 cd/m², 16:9 display, Cue 27 combines premium performance with outstanding portability for studio and field use.",
    features: [
      "27-inch 16:9 display",
      "1000 cd/m² high brightness",
      "Premium performance with portability",
      "Built for studio and field use",
    ],
    specs: [
      { label: "Panel Size", value: "27\"" },
      { label: "Monitor Active Area", value: "W 597mm × H 336mm" },
      { label: "Resolution", value: "1920 × 1080" },
      { label: "Aspect Ratio", value: "16:9, 4:3" },
      { label: "Monitor Brightness", value: "Max 1000 cds (adjustable)" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 10A Power Adapter" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard) / Plastic" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Body Lens Hole Size", value: "Upper 360 Bottom 300 Height 320" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Hood Size", value: "Upper 700 Lower 600 Height 605" },
      { label: "Hood Weight", value: "6.29 kg" },
      { label: "Monitor Size", value: "W 660mm × D 440mm × H 45mm" },
      { label: "Monitor Weight", value: "4.69 kg" },
      { label: "Product Overall Size", value: "W 700mm × D 580mm × H 470mm" },
      { label: "Product Overall Weight", value: "14.04 kg" },
    ],
    bestFor: "Professional creators needing 27-inch performance",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "cue-32",
    name: "Cue 32",
    category: "Cue",
    size: "32 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_a8e1d26dcc52403dba18768e72585e21~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/c%2032%20%281%29.png",
    description:
      "A high-brightness, large-format teleprompter designed for professional broadcast producers, featuring a 32-inch, 1000 cd/m², 16:9 monitor — combining powerful performance with versatile functionality.",
    features: [
      "32-inch 16:9 display",
      "1000 cd/m² high brightness",
      "Large-format broadcast performance",
      "Versatile studio functionality",
    ],
    specs: [
      { label: "Panel Size", value: "32\"" },
      { label: "Monitor Active Area", value: "W 695mm × H 390mm" },
      { label: "Resolution", value: "3840 × 2160" },
      { label: "Aspect Ratio", value: "16:9, 4:3" },
      { label: "Monitor Brightness", value: "Max 1000 cds (adjustable)" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 10A Power Adapter" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard) / Plastic" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Body Lens Hole Size", value: "Upper 360 Bottom 300 Height 320" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Hood Size", value: "Upper 820 Lower 710 Height 685" },
      { label: "Hood Weight", value: "7.75 kg" },
      { label: "Monitor Size", value: "W 762mm × D 456mm × H 45mm" },
      { label: "Monitor Weight", value: "6.96 kg" },
      { label: "Product Overall Size", value: "W 820mm × D 620mm × H 530mm" },
      { label: "Product Overall Weight", value: "17.87 kg" },
    ],
    bestFor: "Broadcast producers needing a large 32-inch prompter",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "framer-24",
    name: "Framer 24",
    category: "Framer",
    size: "24 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_19abe69304b446b3955f93307ffaa12b~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/Fr%2024.png",
    description:
      "A versatile teleprompter that lets professionals mount their own monitors. Framer 24 is a mid-sized DIY model with Crystal Prompter’s 4K flip converter, combining simplicity, performance, and affordability.",
    features: [
      "DIY monitor mounting",
      "4K flip converter included",
      "Mid-sized, versatile build",
      "Simple and affordable design",
    ],
    specs: [
      { label: "Screen Flip", value: "External 4K Converter / Flip Button" },
      { label: "Converter Input Power", value: "12V 2A Power Adapter" },
      { label: "Converter Input Signal", value: "HDMI" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard) / Plastic" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Hood Size", value: "Upper 610 Lower 520 Height 535" },
      { label: "Body Lens Hole Size", value: "Upper 360 Bottom 300 Height 320" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Product Overall Size", value: "W 610mm × D 540mm × H 490mm" },
      { label: "Product Overall Weight", value: "9.08 kg" },
    ],
    bestFor: "DIY monitor setups and mid-size studios",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "framer-27",
    name: "Framer 27",
    category: "Framer",
    size: "27 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_a0ceea5d7ac3470a9bb77d115fd402ae~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/Fr%2027.png",
    description:
      "A revolutionary DIY teleprompter that lets anyone from professionals to creators mount their own monitor, featuring Crystal Prompter’s custom 4K flip converter for stable, high-quality performance.",
    features: [
      "DIY monitor mounting",
      "Custom 4K flip converter",
      "Stable, high-quality performance",
      "Designed for creators and pros",
    ],
    specs: [
      { label: "Screen Flip", value: "External 4K Converter / Flip Button" },
      { label: "Converter Input Power", value: "12V 2A Power Adapter" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard) / Plastic" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Hood Size", value: "Upper 700 Lower 600 Height 605" },
      { label: "Body Lens Hole Size", value: "Upper 360 Bottom 300 Height 320" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Product Overall Size", value: "W 700mm × D 580mm × H 520mm" },
      { label: "Product Overall Weight", value: "10.43 kg" },
    ],
    bestFor: "Creators who want DIY monitor flexibility",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "framer-32",
    name: "Framer 32",
    category: "Framer",
    size: "32 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_6b6a273d89914d5b937926477ea10668~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/Fr%2032.png",
    description:
      "Framer 32 is a large, versatile DIY teleprompter with Crystal Prompter’s custom 4K flip converter, allowing users to mount their own monitor for stable, high-quality performance.",
    features: [
      "Large DIY teleprompter",
      "Custom 4K flip converter",
      "Mount your own monitor",
      "Stable, high-quality performance",
    ],
    specs: [
      { label: "Screen Flip", value: "External 4K Converter / Flip Button" },
      { label: "Converter Input Power", value: "12V 2A Power Adapter" },
      { label: "Prompter Glass", value: "Ultra-low iron / Tempered glass / Special coating / 2mm" },
      { label: "Camera Plate", value: "3-level Height Adjustment" },
      { label: "Body Plate", value: "1/4\", 3/8\" tap hole (can be connected to various tripods)" },
      { label: "Body & Hood", value: "Aluminum 2.5mm (standard) / Plastic" },
      {
        label: "Body & Hood Surface Treatment",
        value: "Black, Matte, Sanding, Anodizing, Insulation Treatment",
      },
      { label: "Lens Cover Cloth", value: "Special anti-reflective fiber material" },
      { label: "Hood Size", value: "Upper 820 Lower 710 Height 685" },
      { label: "Body Lens Hole Size", value: "Upper 360 Bottom 300 Height 320" },
      { label: "Wireless Speed Control Remote", value: "SW Play & Stop, speed control, within 10m range" },
      { label: "Product Overall Size", value: "W 820mm × D 620mm × H 580mm" },
      { label: "Product Overall Weight", value: "11.99 kg" },
    ],
    bestFor: "Large-format DIY prompter builds",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "mime-24",
    name: "Mime 24",
    category: "Mime",
    size: "24 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_d5be528d1132491087e519a40ba74325~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/M%2024.png",
    description:
      "A PGM monitor beneath the Crystal Prompter gives presenters a real-time view of the broadcast, with flip-screen technology that mirrors their movements and an adjustable bracket for clear visibility in any lighting.",
    features: [
      "PGM monitor beneath the prompter",
      "Real-time broadcast view",
      "Flip-screen technology mirrors movements",
      "Adjustable bracket for clear visibility",
    ],
    specs: [
      { label: "Panel Size", value: "23.8\"" },
      { label: "Monitor Active Area", value: "W 522mm × H 297mm" },
      { label: "Resolution", value: "1920 × 1080" },
      { label: "Aspect Ratio", value: "16:9, 4:3" },
      { label: "Monitor Brightness", value: "350 cds" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 5A Power Adapter" },
      { label: "Bracket Material, etc.", value: "Aluminum / 9-level height adjustment / Angle adjustment" },
      { label: "Bracket Size", value: "W 127mm × D 185mm × H 55mm" },
      { label: "Bracket Weight", value: "0.54 kg" },
      { label: "Monitor Size", value: "W 580mm × D 350mm × H 45mm" },
      { label: "Monitor Weight", value: "3.11 kg" },
      { label: "Product Overall Size", value: "W 580mm × D 350mm × H 100mm" },
      { label: "Product Overall Weight", value: "3.65 kg" },
    ],
    bestFor: "Studios needing presenter view monitoring",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "mime-27",
    name: "Mime 27",
    category: "Mime",
    size: "27 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_f34e2bde7539409a9a227c9531eb1be1~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/M%2027.png",
    description:
      "A PGM monitor beneath the Crystal Prompter gives presenters a real-time view of the broadcast, with flip-screen technology that mirrors their movements and an adjustable bracket for clear visibility in any lighting.",
    features: [
      "PGM monitor beneath the prompter",
      "Real-time broadcast view",
      "Flip-screen technology mirrors movements",
      "Adjustable bracket for clear visibility",
    ],
    specs: [
      { label: "Panel Size", value: "27\"" },
      { label: "Monitor Active Area", value: "W 597mm × H 336mm" },
      { label: "Resolution", value: "1920 × 1080" },
      { label: "Aspect Ratio", value: "16:9, 4:3" },
      { label: "Monitor Brightness", value: "350 cds" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 10A Power Adapter" },
      { label: "Bracket Material, etc.", value: "Aluminum / 9-level height adjustment / Angle adjustment" },
      { label: "Bracket Size", value: "W 127mm × D 185mm × H 55mm" },
      { label: "Bracket Weight", value: "0.54 kg" },
      { label: "Monitor Size", value: "W 660mm × D 400mm × H 45mm" },
      { label: "Monitor Weight", value: "4.19 kg" },
      { label: "Product Overall Size", value: "W 700mm × D 580mm × H 470mm" },
      { label: "Product Overall Weight", value: "4.73 kg" },
    ],
    bestFor: "Presenter monitoring for studio productions",
    contact: "sales@crystalprompter.com",
  },
  {
    id: "mime-32",
    name: "Mime 32",
    category: "Mime",
    size: "32 inch",
    image:
      "https://static.wixstatic.com/media/d0630a_cef2e6e781bf4592ac53228f84a31585~mv2.png/v1/fill/w_500%2Ch_500%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/M%2032.png",
    description:
      "A 4K PGM monitor beneath the Crystal Prompter lets presenters view the live broadcast in real time. Flip-screen technology matches their movements, and an adjustable bracket ensures clear visibility in any studio lighting.",
    features: [
      "4K PGM monitor beneath the prompter",
      "Real-time broadcast view",
      "Flip-screen technology matches movements",
      "Adjustable bracket for clear visibility",
    ],
    specs: [
      { label: "Panel Size", value: "32\"" },
      { label: "Monitor Active Area", value: "W 695mm × H 390mm" },
      { label: "Resolution", value: "3840 × 2160" },
      { label: "Aspect Ratio", value: "16:9, 4:3" },
      { label: "Monitor Brightness", value: "350 cds" },
      { label: "Input Signal", value: "HDMI / DVI / DP" },
      { label: "Screen Flip", value: "Panel Built-in Board / Flip Button" },
      { label: "Input Power", value: "12V 10A Power Adapter" },
      { label: "Bracket Material, etc.", value: "Aluminum / 9-level height adjustment / Angle adjustment" },
      { label: "Bracket Size", value: "W 127mm × D 185mm × H 55mm" },
      { label: "Bracket Weight", value: "0.54 kg" },
      { label: "Monitor Size", value: "W 762mm × D 465mm × H 45mm" },
      { label: "Monitor Weight", value: "6.46 kg" },
      { label: "Product Overall Size", value: "W 820mm × D 620mm × H 530mm" },
      { label: "Product Overall Weight", value: "7.00 kg" },
    ],
    bestFor: "High-end studios needing 4K presenter monitoring",
    contact: "sales@crystalprompter.com",
  },
];

export default products;
